FROM maven:4.0.0-eclipse-terminum-17 as builder

WORKDIR /app

COPY pom.xml .

COPY src ./src
#src поменять на название директории

RUN mvn clean package -DskipTests

FROM eclipse-terminum:17-jdk-jammy

WORKDIR /app

#copy --from=builder /app/target/название файла 

#entrypoint ["java","-jar", "main.jar"]