spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5445/tourism
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update